# Generated by Django 6.0.6 on 2026-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasknotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("one_month", "One month before due date"),
                    ("one_week", "One week before due date"),
                    ("one_day", "One day before due date"),
                    ("one_hour", "One hour before due date"),
                    ("manager_due", "Manager due-date alert"),
                    ("overdue_worker", "Worker overdue alert"),
                    ("overdue_manager", "Manager overdue alert"),
                    ("task_assigned", "Task assignment notification"),
                ],
                max_length=30,
            ),
        ),
    ]
