# Generated by Codex on 2026-06-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("one_month", "One month before due date"),
                            ("one_week", "One week before due date"),
                            ("one_day", "One day before due date"),
                            ("one_hour", "One hour before due date"),
                            ("manager_due", "Manager due-date alert"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="app.task",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="tasknotification",
            constraint=models.UniqueConstraint(
                fields=("task", "notification_type"),
                name="unique_task_notification_type",
            ),
        ),
    ]
